from .tester import TesterBot
from .obsapi import OBSBot
from .spotifyapi import SpotifyBot
from .tarkov import TarkovBot
from .subathon import SubathonBot
from .skynet import AIBot
from .goals import GoalBot
from .ban import BannedBot
from .tts import generate_speech